# Generated by Django 5.2.7 on 2025-11-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_sale_branch_alter_sale_total_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
