# Generated by Django 5.2.7 on 2025-11-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pieces_per_pack',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('pack', 'Pack'), ('piece', 'Piece')], default='pack', max_length=10),
        ),
    ]
