# Generated by Django 5.2.7 on 2025-11-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_pieces_per_pack_product_unit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_per_pack',
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_piece',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
