# Generated by Django 5.2.7 on 2025-11-17 15:52

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_no',
            field=models.CharField(default=inventory.models.generate_batch_no, max_length=50, unique=True),
        ),
    ]
