# Generated by Django 5.2.7 on 2025-11-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='batches', to='inventory.purchaseorder'),
        ),
    ]
