# Generated by Django 5.2.7 on 2025-11-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='batched',
            field=models.BooleanField(default=False),
        ),
    ]
