# Generated by Django 5.2.7 on 2025-11-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_purchaseorder_batched'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_price_per_pack',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price_per_piece',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
