# Generated by Django 5.2.7 on 2025-11-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unit',
            field=models.CharField(choices=[('p', 'Piece'), ('w', 'Whole')], default='w', max_length=1),
        ),
    ]
