# Generated by Django 5.2.7 on 2025-11-22 11:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_saleitem_discount_saleitem_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.branch'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5),
        ),
    ]
