# Generated by Django 5.2.7 on 2025-11-23 08:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_sale_branch_alter_saleitem_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='vat',
            new_name='vat_rate',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
