# Generated by Django 5.2.7 on 2025-11-23 08:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_rename_vat_saleitem_vat_rate_saleitem_vat_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='vat_rate',
            new_name='vat',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='vat_amount',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
