# Generated by Django 5.2.7 on 2025-12-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_sale_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='posted_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
