# Generated by Django 5.2.7 on 2025-12-15 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_sale_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.branch'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(default='Walk-in', max_length=255),
        ),
    ]
